In [1]:
import pandas as pd

## Data Load

In [2]:
q1_total = pd.read_csv('q1_total.csv')
del q1_total['Unnamed: 0']
q1_total.head()

,jur_stn,date,pub_cnt,vio_total_cnt,report_sx_남성_x,report_sx_불상_x,report_sx_여성_x,rob_total_cnt,report_sx_남성_y,report_sx_불상_y,...,sx_rate_65세이상,foreign_num,light_cnt,cctv_cnt,bell_cnt,rob_safety_q1,mur_safety_q2,ta_safety_q3,raw_odder_q4,overall_q5
0,서울중부경찰서,2018(상반기),204.0,1540.0,177.0,11.0,120.0,635.0,92.0,2.0,...,75.2,11988.0,4933.0,1563.0,406.0,79.3,80.7,67.3,66.4,74.0
1,서울중부경찰서,2018(하반기),204.0,1638.0,984.0,48.0,606.0,664.0,431.0,6.0,...,75.2,11988.0,4933.0,1563.0,406.0,79.0,80.5,71.8,70.0,76.0
2,서울종로경찰서,2018(상반기),150.0,600.0,62.0,6.0,52.0,210.0,26.0,0.0,...,77.1,12056.0,5259.0,1500.0,450.0,78.0,81.2,69.6,60.3,73.3
3,서울종로경찰서,2018(하반기),150.0,827.0,519.0,28.0,280.0,264.0,172.0,5.0,...,77.1,12056.0,5259.0,1500.0,450.0,86.7,87.1,76.1,68.4,79.3
4,서울남대문경찰서,2018(상반기),88.0,1095.0,148.0,5.0,66.0,410.0,57.0,0.0,...,75.2,11988.0,3000.0,1500.0,203.0,77.8,80.6,69.2,67.9,73.6

In [3]:
q1_total.columns

Index(['jur_stn', 'date', 'pub_cnt', 'vio_total_cnt', 'report_sx_남성_x',
       'report_sx_불상_x', 'report_sx_여성_x', 'rob_total_cnt', 'report_sx_남성_y',
       'report_sx_불상_y', 'report_sx_여성_y', 'report_total_cnt', 'report_sx_남성',
       'report_sx_불상', 'report_sx_여성', 'poor_num', 'poor_ratio',
       'Unnamed: 0.1', 'age_합계', 'age_15세미만', 'age_15~64세', 'age_65세이상',
       'age_평균연령', 'sx_rate_합계', 'sx_rate_15세미만', 'sx_rate_15~64세',
       'sx_rate_65세이상', 'foreign_num', 'light_cnt', 'cctv_cnt', 'bell_cnt',
       'rob_safety_q1', 'mur_safety_q2', 'ta_safety_q3', 'raw_odder_q4',
       'overall_q5'],
      dtype='object')

In [4]:
# 법질서준수도에서 쓸 데이터만 남김
q4_info = q1_total[['jur_stn', 'date', 'pub_cnt', 'poor_num', 'age_합계', 'age_15세미만',
       'age_15~64세', 'age_65세이상', 'age_평균연령', 'sx_rate_합계', 'sx_rate_15세미만',
       'sx_rate_15~64세', 'sx_rate_65세이상', 'foreign_num', 'cctv_cnt', 'bell_cnt',
       'light_cnt', 'raw_odder_q4']]
q4_info.head()

,jur_stn,date,pub_cnt,poor_num,age_합계,age_15세미만,age_15~64세,age_65세이상,age_평균연령,sx_rate_합계,sx_rate_15세미만,sx_rate_15~64세,sx_rate_65세이상,foreign_num,cctv_cnt,bell_cnt,light_cnt,raw_odder_q4
0,서울중부경찰서,2018(상반기),204.0,23097.0,129797.0,10876.0,99167.0,19754.0,43.0,94.2,101.8,97.7,75.2,11988.0,1563.0,406.0,4933.0,66.4
1,서울중부경찰서,2018(하반기),204.0,23956.0,129797.0,10876.0,99167.0,19754.0,43.0,94.2,101.8,97.7,75.2,11988.0,1563.0,406.0,4933.0,70.0
2,서울종로경찰서,2018(상반기),150.0,21719.0,157967.0,13201.0,120719.0,24047.0,42.3,95.5,104.7,98.6,77.1,12056.0,1500.0,450.0,5259.0,60.3
3,서울종로경찰서,2018(하반기),150.0,22112.0,157967.0,13201.0,120719.0,24047.0,42.3,95.5,104.7,98.6,77.1,12056.0,1500.0,450.0,5259.0,68.4
4,서울남대문경찰서,2018(상반기),88.0,23097.0,129797.0,10876.0,99167.0,19754.0,43.0,94.2,101.8,97.7,75.2,11988.0,1500.0,203.0,3000.0,67.9

### 전국112신고접수 데이터 출처 : 스마트치안빅데이터플랫폼 '전국112신고접수' (경찰청 제공)
- 링크 : https://www.bigdata-policing.kr/policy/contents/policy-dataSearch.do?schM=View&dbiIdx=23

In [5]:
report_data = pd.read_csv('./data/전국112신고접수.csv')
del report_data['Unnamed: 0']
report_data.head()

,접수년월,경찰서명,신고 건수(전체),신고 성별(남자),신고 성별(여자),신고 성별(불상),신고 성별(기타),접수긴급유형(긴급),접수긴급유형(중요),접수긴급유형(일반),...,발생시간대(14),발생시간대(15),발생시간대(16),발생시간대(17),발생시간대(18),발생시간대(19),발생시간대(20),발생시간대(21),발생시간대(22),발생시간대(23)
0,201801,서울금천경찰서,5703,3319,1665,719,0,29,1274,3014,...,218,274,252,270,288,301,359,331,336,366
1,201801,서울동대문경찰서,6530,3774,1892,862,2,28,1454,3367,...,307,314,299,327,398,325,328,339,362,412
2,201801,서울마포경찰서,8459,5037,2342,1077,3,53,2181,4675,...,292,298,306,278,350,315,356,409,469,530
3,201801,서울은평경찰서,4456,2423,1428,603,2,29,1062,2465,...,172,185,192,186,205,231,214,244,280,311
4,201801,서울구로경찰서,7189,4183,2113,891,2,56,1809,3850,...,333,336,341,330,363,403,427,451,449,445

# -------------------------------------------------

## Data Check

In [6]:
report_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1458 entries, 0 to 1457
Data columns (total 43 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   접수년월        1458 non-null   int64
 1   경찰서명        1458 non-null   object
 2   신고 건수(전체)   1458 non-null   int64
 3   신고 성별(남자)   1458 non-null   int64
 4   신고 성별(여자)   1458 non-null   int64
 5   신고 성별(불상)   1458 non-null   int64
 6   신고 성별(기타)   1458 non-null   int64
 7   접수긴급유형(긴급)  1458 non-null   int64
 8   접수긴급유형(중요)  1458 non-null   int64
 9   접수긴급유형(일반)  1458 non-null   int64
 10  접수긴급유형(민원)  1458 non-null   int64
 11  접수긴급유형(기타)  1458 non-null   int64
 12  발생요일(일)     1458 non-null   int64
 13  발생요일(월)     1458 non-null   int64
 14  발생요일(화)     1458 non-null   int64
 15  발생요일(수)     1458 non-null   int64
 16  발생요일(목)     1458 non-null   int64
 17  발생요일(금)     1458 non-null   int64
 18  발생요일(토)     1458 non-null   int64
 19  발생시간대(00)   1458 non-null   int64
 20  발생시간대(01)   1458 non-null   int64
 21  발생시간대(02)   1458 non-null   int64
 22  발생시간대(03)   1458 non-null   int64
 23  발생시간대(04)   1458 non-null   int64
 24  발생시간대(05)   1458 non-null   int64
 25  발생시간대(06)   1458 non-null   int64
 26  발생시간대(07)   1458 non-null   int64
 27  발생시간대(08)   1458 non-null   int64
 28  발생시간대(09)   1458 non-null   int64
 29  발생시간대(10)   1458 non-null   int64
 30  발생시간대(11)   1458 non-null   int64
 31  발생시간대(12)   1458 non-null   int64
 32  발생시간대(13)   1458 non-null   int64
 33  발생시간대(14)   1458 non-null   int64
 34  발생시간대(15)   1458 non-null   int64
 35  발생시간대(16)   1458 non-null   int64
 36  발생시간대(17)   1458 non-null   int64
 37  발생시간대(18)   1458 non-null   int64
 38  발생시간대(19)   1458 non-null   int64
 39  발생시간대(20)   1458 non-null   int64
 40  발생시간대(21)   1458 non-null   int64
 41  발생시간대(22)   1458 non-null   int64
 42  발생시간대(23)   1458 non-null   int64
dtypes: int64(42), object(1)
memory usage: 489.9+ KB

In [7]:
# 발생시간대 재분류
report_data['새벽(01~05)'] = report_data['발생시간대(01)'] + report_data['발생시간대(05)']
report_data['아침(06~10)'] = report_data['발생시간대(06)'] + report_data['발생시간대(10)']
report_data['점심(11~14)'] = report_data['발생시간대(11)'] + report_data['발생시간대(14)']
report_data['오후(15~18)'] =report_data['발생시간대(15)'] + report_data['발생시간대(18)']
report_data['저녁(19~21)'] = report_data['발생시간대(19)'] + report_data['발생시간대(21)']
report_data['심야(22~00)'] = report_data['발생시간대(22)'] + report_data['발생시간대(00)']

In [8]:
report_data.columns

Index(['접수년월', '경찰서명', '신고 건수(전체)', '신고 성별(남자)', '신고 성별(여자)', '신고 성별(불상)',
       '신고 성별(기타)', '접수긴급유형(긴급)', '접수긴급유형(중요)', '접수긴급유형(일반)', '접수긴급유형(민원)',
       '접수긴급유형(기타)', '발생요일(일)', '발생요일(월)', '발생요일(화)', '발생요일(수)', '발생요일(목)',
       '발생요일(금)', '발생요일(토)', '발생시간대(00)', '발생시간대(01)', '발생시간대(02)',
       '발생시간대(03)', '발생시간대(04)', '발생시간대(05)', '발생시간대(06)', '발생시간대(07)',
       '발생시간대(08)', '발생시간대(09)', '발생시간대(10)', '발생시간대(11)', '발생시간대(12)',
       '발생시간대(13)', '발생시간대(14)', '발생시간대(15)', '발생시간대(16)', '발생시간대(17)',
       '발생시간대(18)', '발생시간대(19)', '발생시간대(20)', '발생시간대(21)', '발생시간대(22)',
       '발생시간대(23)', '새벽(01~05)', '아침(06~10)', '점심(11~14)', '오후(15~18)',
       '저녁(19~21)', '심야(22~00)'],
      dtype='object')

In [9]:
report_data.drop(['발생시간대(00)', '발생시간대(01)', '발생시간대(02)',
       '발생시간대(03)', '발생시간대(04)', '발생시간대(05)', '발생시간대(06)', '발생시간대(07)',
       '발생시간대(08)', '발생시간대(09)', '발생시간대(10)', '발생시간대(11)', '발생시간대(12)',
       '발생시간대(13)', '발생시간대(14)', '발생시간대(15)', '발생시간대(16)', '발생시간대(17)',
       '발생시간대(18)', '발생시간대(19)', '발생시간대(20)', '발생시간대(21)', '발생시간대(22)',
       '발생시간대(23)'], axis=1, inplace=True) # 기존 컬럼 drop

In [10]:
report_data['date'] = report_data['접수년월'].apply(lambda x : str(x)[:4] + '(상반기)' if  int(str(x)[-2:]) < 7 else str(x)[:4] + '(하반기)' )
report_data = report_data.rename(columns={'경찰서명' : 'jur_stn'})
report_data.head() # date, jur_stn 양식 맞춰줌

,접수년월,jur_stn,신고 건수(전체),신고 성별(남자),신고 성별(여자),신고 성별(불상),신고 성별(기타),접수긴급유형(긴급),접수긴급유형(중요),접수긴급유형(일반),...,발생요일(목),발생요일(금),발생요일(토),새벽(01~05),아침(06~10),점심(11~14),오후(15~18),저녁(19~21),심야(22~00),date
0,201801,서울금천경찰서,5703,3319,1665,719,0,29,1274,3014,...,799,814,829,380,298,406,562,632,696,2018(상반기)
1,201801,서울동대문경찰서,6530,3774,1892,862,2,28,1454,3367,...,781,843,946,437,340,573,712,664,725,2018(상반기)
2,201801,서울마포경찰서,8459,5037,2342,1077,3,53,2181,4675,...,966,1119,1335,881,563,558,648,724,1108,2018(상반기)
3,201801,서울은평경찰서,4456,2423,1428,603,2,29,1062,2465,...,573,482,657,364,229,335,390,475,561,2018(상반기)
4,201801,서울구로경찰서,7189,4183,2113,891,2,56,1809,3850,...,912,940,995,519,359,590,699,854,928,2018(상반기)

### Q4 X값 생성
- 기존 report data를 상, 하반기 sum 값으로 묶어 X값으로 사용

In [11]:
report_data_df = report_data.groupby(['jur_stn','date']).sum()
report_data_df.reset_index(inplace=True)
report_data_df.head(3) # 상, 하반기별 총합 계산

,jur_stn,date,접수년월,신고 건수(전체),신고 성별(남자),신고 성별(여자),신고 성별(불상),신고 성별(기타),접수긴급유형(긴급),접수긴급유형(중요),...,발생요일(수),발생요일(목),발생요일(금),발생요일(토),새벽(01~05),아침(06~10),점심(11~14),오후(15~18),저녁(19~21),심야(22~00)
0,마산동부경찰서,2018(상반기),1210821,18949,11186,5678,2076,9,70,2218,...,2645,2529,2797,3177,1302,1036,1460,1786,2201,2462
1,마산동부경찰서,2018(하반기),1210857,20677,12327,6339,2004,7,125,2318,...,2770,2754,3061,3445,1457,1149,1522,1989,2403,2558
2,마산동부경찰서,2019(상반기),1211421,23939,14081,7248,2596,14,272,3326,...,3580,3252,3526,3820,1454,1362,2003,2417,2768,2735

In [12]:
report_data_df.drop('접수년월', axis=1, inplace=True) # 접수년월 col 제외

In [13]:
report_data_df['date'].value_counts()

2018(하반기)    41
2018(상반기)    41
2019(상반기)    41
2020(하반기)    40
2020(상반기)    40
2019(하반기)    40
Name: date, dtype: int64

## 최종 Merge

In [14]:
# feature로 사용될 데이터 종합
law_df = pd.merge(report_data_df, q4_info, on=['jur_stn','date'], how='right')
law_df.head(3)

,jur_stn,date,신고 건수(전체),신고 성별(남자),신고 성별(여자),신고 성별(불상),신고 성별(기타),접수긴급유형(긴급),접수긴급유형(중요),접수긴급유형(일반),...,age_평균연령,sx_rate_합계,sx_rate_15세미만,sx_rate_15~64세,sx_rate_65세이상,foreign_num,cctv_cnt,bell_cnt,light_cnt,raw_odder_q4
0,서울중부경찰서,2018(상반기),23968.0,14066.0,6106.0,3787.0,9.0,129.0,4815.0,13416.0,...,43.0,94.2,101.8,97.7,75.2,11988.0,1563.0,406.0,4933.0,66.4
1,서울중부경찰서,2018(하반기),26222.0,15718.0,6925.0,3571.0,8.0,148.0,5031.0,15480.0,...,43.0,94.2,101.8,97.7,75.2,11988.0,1563.0,406.0,4933.0,70.0
2,서울종로경찰서,2018(상반기),15558.0,8823.0,4342.0,2361.0,32.0,52.0,2807.0,8504.0,...,42.3,95.5,104.7,98.6,77.1,12056.0,1500.0,450.0,5259.0,60.3

In [15]:
law_df['date'].value_counts()

2018(하반기)    41
2020(하반기)    41
2018(상반기)    41
2020(상반기)    41
2019(상반기)    41
2019(하반기)    41
Name: date, dtype: int64

In [16]:
law_df[law_df['신고 건수(전체)'].isnull()] # null 값 확인

,jur_stn,date,신고 건수(전체),신고 성별(남자),신고 성별(여자),신고 성별(불상),신고 성별(기타),접수긴급유형(긴급),접수긴급유형(중요),접수긴급유형(일반),...,age_평균연령,sx_rate_합계,sx_rate_15세미만,sx_rate_15~64세,sx_rate_65세이상,foreign_num,cctv_cnt,bell_cnt,light_cnt,raw_odder_q4
151,세종경찰서,2019(하반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.3,101.366667,103.166667,104.6,75.9,6933.666667,2527.0,100.0,10410.0,71.7
232,세종경찰서,2020(상반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.3,101.366667,103.166667,104.6,75.9,6933.666667,2527.0,100.0,10410.0,NaN
233,세종경찰서,2020(하반기),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.3,101.366667,103.166667,104.6,75.9,6933.666667,2527.0,100.0,10410.0,NaN

In [17]:
## 세종 null 값 index 채우기 ##
null_index= law_df[law_df['신고 건수(전체)'].isnull()].index 
sejong_mean = law_df[(law_df['jur_stn'].str.contains('세종')) & (law_df['신고 건수(전체)'].notnull()) ].mean()
law_df.columns

Index(['jur_stn', 'date', '신고 건수(전체)', '신고 성별(남자)', '신고 성별(여자)', '신고 성별(불상)',
       '신고 성별(기타)', '접수긴급유형(긴급)', '접수긴급유형(중요)', '접수긴급유형(일반)', '접수긴급유형(민원)',
       '접수긴급유형(기타)', '발생요일(일)', '발생요일(월)', '발생요일(화)', '발생요일(수)', '발생요일(목)',
       '발생요일(금)', '발생요일(토)', '새벽(01~05)', '아침(06~10)', '점심(11~14)',
       '오후(15~18)', '저녁(19~21)', '심야(22~00)', 'pub_cnt', 'poor_num', 'age_합계',
       'age_15세미만', 'age_15~64세', 'age_65세이상', 'age_평균연령', 'sx_rate_합계',
       'sx_rate_15세미만', 'sx_rate_15~64세', 'sx_rate_65세이상', 'foreign_num',
       'cctv_cnt', 'bell_cnt', 'light_cnt', 'raw_odder_q4'],
      dtype='object')

In [18]:
law_df.columns[2:-1]

Index(['신고 건수(전체)', '신고 성별(남자)', '신고 성별(여자)', '신고 성별(불상)', '신고 성별(기타)',
       '접수긴급유형(긴급)', '접수긴급유형(중요)', '접수긴급유형(일반)', '접수긴급유형(민원)', '접수긴급유형(기타)',
       '발생요일(일)', '발생요일(월)', '발생요일(화)', '발생요일(수)', '발생요일(목)', '발생요일(금)',
       '발생요일(토)', '새벽(01~05)', '아침(06~10)', '점심(11~14)', '오후(15~18)',
       '저녁(19~21)', '심야(22~00)', 'pub_cnt', 'poor_num', 'age_합계', 'age_15세미만',
       'age_15~64세', 'age_65세이상', 'age_평균연령', 'sx_rate_합계', 'sx_rate_15세미만',
       'sx_rate_15~64세', 'sx_rate_65세이상', 'foreign_num', 'cctv_cnt',
       'bell_cnt', 'light_cnt'],
      dtype='object')

In [19]:
for i in null_index :
    for c in law_df.columns[2:-5] :
#         print(i, c)
#         print(q1_total.loc[i, c])
        law_df.loc[i, c] = sejong_mean[c]

In [20]:
law_df[law_df['jur_stn'].str.contains('세종')]

,jur_stn,date,신고 건수(전체),신고 성별(남자),신고 성별(여자),신고 성별(불상),신고 성별(기타),접수긴급유형(긴급),접수긴급유형(중요),접수긴급유형(일반),...,age_평균연령,sx_rate_합계,sx_rate_15세미만,sx_rate_15~64세,sx_rate_65세이상,foreign_num,cctv_cnt,bell_cnt,light_cnt,raw_odder_q4
68,세종경찰서,2018(상반기),8889.000000,5080.0,2273.0,1534.0,2.000000,28.0,903.0,5475.000000,...,36.2,101.400000,103.200000,104.7,75.5,6486.000000,2527.0,100.0,10410.0,69.0
69,세종경찰서,2018(하반기),10593.000000,6050.0,2775.0,1765.0,3.000000,68.0,1207.0,6605.000000,...,36.2,101.400000,103.200000,104.7,75.5,6486.000000,2527.0,100.0,10410.0,71.6
150,세종경찰서,2019(상반기),21278.000000,11388.0,6028.0,3853.0,9.000000,159.0,2840.0,12602.000000,...,36.5,101.300000,103.100000,104.4,76.7,7829.000000,2527.0,100.0,10410.0,74.2
151,세종경찰서,2019(하반기),13586.666667,7506.0,3692.0,2384.0,4.666667,85.0,1650.0,8227.333333,...,36.3,101.366667,103.166667,104.6,75.9,6933.666667,2527.0,100.0,10410.0,71.7
232,세종경찰서,2020(상반기),13586.666667,7506.0,3692.0,2384.0,4.666667,85.0,1650.0,8227.333333,...,36.3,101.366667,103.166667,104.6,75.9,6933.666667,2527.0,100.0,10410.0,NaN
233,세종경찰서,2020(하반기),13586.666667,7506.0,3692.0,2384.0,4.666667,85.0,1650.0,8227.333333,...,36.3,101.366667,103.166667,104.6,75.9,6933.666667,2527.0,100.0,10410.0,NaN

In [21]:
law_df.columns

Index(['jur_stn', 'date', '신고 건수(전체)', '신고 성별(남자)', '신고 성별(여자)', '신고 성별(불상)',
       '신고 성별(기타)', '접수긴급유형(긴급)', '접수긴급유형(중요)', '접수긴급유형(일반)', '접수긴급유형(민원)',
       '접수긴급유형(기타)', '발생요일(일)', '발생요일(월)', '발생요일(화)', '발생요일(수)', '발생요일(목)',
       '발생요일(금)', '발생요일(토)', '새벽(01~05)', '아침(06~10)', '점심(11~14)',
       '오후(15~18)', '저녁(19~21)', '심야(22~00)', 'pub_cnt', 'poor_num', 'age_합계',
       'age_15세미만', 'age_15~64세', 'age_65세이상', 'age_평균연령', 'sx_rate_합계',
       'sx_rate_15세미만', 'sx_rate_15~64세', 'sx_rate_65세이상', 'foreign_num',
       'cctv_cnt', 'bell_cnt', 'light_cnt', 'raw_odder_q4'],
      dtype='object')

In [22]:
law_df['report_ratio'] = round(law_df['신고 건수(전체)'] / law_df['age_합계'], 2)
law_df.head() # 인구대비 신고율

,jur_stn,date,신고 건수(전체),신고 성별(남자),신고 성별(여자),신고 성별(불상),신고 성별(기타),접수긴급유형(긴급),접수긴급유형(중요),접수긴급유형(일반),...,sx_rate_합계,sx_rate_15세미만,sx_rate_15~64세,sx_rate_65세이상,foreign_num,cctv_cnt,bell_cnt,light_cnt,raw_odder_q4,report_ratio
0,서울중부경찰서,2018(상반기),23968.0,14066.0,6106.0,3787.0,9.0,129.0,4815.0,13416.0,...,94.2,101.8,97.7,75.2,11988.0,1563.0,406.0,4933.0,66.4,0.18
1,서울중부경찰서,2018(하반기),26222.0,15718.0,6925.0,3571.0,8.0,148.0,5031.0,15480.0,...,94.2,101.8,97.7,75.2,11988.0,1563.0,406.0,4933.0,70.0,0.20
2,서울종로경찰서,2018(상반기),15558.0,8823.0,4342.0,2361.0,32.0,52.0,2807.0,8504.0,...,95.5,104.7,98.6,77.1,12056.0,1500.0,450.0,5259.0,60.3,0.10
3,서울종로경찰서,2018(하반기),16897.0,10013.0,4643.0,2213.0,28.0,94.0,2941.0,9949.0,...,95.5,104.7,98.6,77.1,12056.0,1500.0,450.0,5259.0,68.4,0.11
4,서울남대문경찰서,2018(상반기),16686.0,10045.0,4263.0,2373.0,5.0,81.0,3134.0,9367.0,...,94.2,101.8,97.7,75.2,11988.0,1500.0,203.0,3000.0,67.9,0.13

In [23]:
q4_df = law_df.copy()
q4_df['date'].value_counts()

2018(하반기)    41
2020(하반기)    41
2018(상반기)    41
2020(상반기)    41
2019(상반기)    41
2019(하반기)    41
Name: date, dtype: int64

In [24]:
q4_df.to_csv('q4_df.csv') # 최종

## X , y data

In [25]:
# q4 data에서 X,y data 분리
X_data = q4_df.drop('raw_odder_q4',axis=1)
y_data = q4_df['raw_odder_q4'].dropna()

In [26]:
# 2020 년도는 y값이 없으므로 제외하고 eval data로 포함
X_data = X_data.drop(X_data[X_data['date'].str.contains('2020')].index)
X_data.head()

,jur_stn,date,신고 건수(전체),신고 성별(남자),신고 성별(여자),신고 성별(불상),신고 성별(기타),접수긴급유형(긴급),접수긴급유형(중요),접수긴급유형(일반),...,age_평균연령,sx_rate_합계,sx_rate_15세미만,sx_rate_15~64세,sx_rate_65세이상,foreign_num,cctv_cnt,bell_cnt,light_cnt,report_ratio
0,서울중부경찰서,2018(상반기),23968.0,14066.0,6106.0,3787.0,9.0,129.0,4815.0,13416.0,...,43.0,94.2,101.8,97.7,75.2,11988.0,1563.0,406.0,4933.0,0.18
1,서울중부경찰서,2018(하반기),26222.0,15718.0,6925.0,3571.0,8.0,148.0,5031.0,15480.0,...,43.0,94.2,101.8,97.7,75.2,11988.0,1563.0,406.0,4933.0,0.20
2,서울종로경찰서,2018(상반기),15558.0,8823.0,4342.0,2361.0,32.0,52.0,2807.0,8504.0,...,42.3,95.5,104.7,98.6,77.1,12056.0,1500.0,450.0,5259.0,0.10
3,서울종로경찰서,2018(하반기),16897.0,10013.0,4643.0,2213.0,28.0,94.0,2941.0,9949.0,...,42.3,95.5,104.7,98.6,77.1,12056.0,1500.0,450.0,5259.0,0.11
4,서울남대문경찰서,2018(상반기),16686.0,10045.0,4263.0,2373.0,5.0,81.0,3134.0,9367.0,...,43.0,94.2,101.8,97.7,75.2,11988.0,1500.0,203.0,3000.0,0.13

In [27]:
# 2020년 데이터로 eval data 생성
del_idx = q4_df[q4_df['raw_odder_q4'].notnull()].index
eval_X_data = q4_df.drop(del_idx)
eval_X_data=  eval_X_data.drop('raw_odder_q4',axis=1)

In [28]:
X_data['date'].value_counts()

2018(하반기)    41
2019(상반기)    41
2019(하반기)    41
2018(상반기)    41
Name: date, dtype: int64

In [29]:
eval_X_data['date'].value_counts()

2020(상반기)    41
2020(하반기)    41
Name: date, dtype: int64

In [30]:
X_data.shape, y_data.shape

((164, 41), (164,))

In [31]:
eval_X_data.shape

(82, 41)

In [32]:
# train data save
eval_X_data.reset_index(drop=True,inplace=True)
train_data = pd.concat([X_data,y_data.dropna()],axis=1)
train_data.to_csv("./analysis/q4_train.csv",index=0)
eval_X_data.to_csv("./analysis/q4_target.csv",index=0)